// This file is automatically generated. Do not edit it directly.
import { createClient, SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || '';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || '';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Check if Supabase is properly configured
const isSupabaseConfigured = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);

// Create a mock client when Supabase is not configured
// This allows the app to run without authentication features
const createMockClient = (): SupabaseClient<Database> => {
  if (typeof window !== 'undefined') {
    console.warn('[Supabase] Environment variables not configured. Authentication features will be disabled.');
  }
  
  const notConfiguredError = { message: 'Supabase not configured. Please set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY environment variables.' };
  
  return {
    auth: {
      getSession: () => Promise.resolve({ data: { session: null }, error: null }),
      onAuthStateChange: () => ({ data: { subscription: { unsubscribe: () => {} } } }),
      signUp: () => Promise.resolve({ data: { user: null, session: null }, error: notConfiguredError }),
      signInWithPassword: () => Promise.resolve({ data: { user: null, session: null }, error: notConfiguredError }),
      signOut: () => Promise.resolve({ error: null }),
    },
  } as unknown as SupabaseClient<Database>;
};

const createSupabaseClient = (): SupabaseClient<Database> => {
  if (!isSupabaseConfigured) {
    return createMockClient();
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
};

export const supabase = createSupabaseClient();
export { isSupabaseConfigured };